//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buhtig.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buhtig.Resources.Strings.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Buhtig 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Import 的本地化字符串。
        /// </summary>
        public static string BatchImport {
            get {
                return ResourceManager.GetString("BatchImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charts 的本地化字符串。
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone 的本地化字符串。
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cloning... 的本地化字符串。
        /// </summary>
        public static string Cloning {
            get {
                return ResourceManager.GetString("Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inner Commit Root 的本地化字符串。
        /// </summary>
        public static string CommitRootMessage {
            get {
                return ResourceManager.GetString("CommitRootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commits 的本地化字符串。
        /// </summary>
        public static string Commits {
            get {
                return ResourceManager.GetString("Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element 的本地化字符串。
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estimated 的本地化字符串。
        /// </summary>
        public static string Estimated {
            get {
                return ResourceManager.GetString("Estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Path 的本地化字符串。
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Framework 的本地化字符串。
        /// </summary>
        public static string Framework {
            get {
                return ResourceManager.GetString("Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Git Email 的本地化字符串。
        /// </summary>
        public static string GitEmail {
            get {
                return ResourceManager.GetString("GitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Git Name 的本地化字符串。
        /// </summary>
        public static string GitName {
            get {
                return ResourceManager.GetString("GitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lines Added 的本地化字符串。
        /// </summary>
        public static string LinesAdded {
            get {
                return ResourceManager.GetString("LinesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lines Deleted 的本地化字符串。
        /// </summary>
        public static string LinesDeleted {
            get {
                return ResourceManager.GetString("LinesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Path : 的本地化字符串。
        /// </summary>
        public static string LocalPath {
            get {
                return ResourceManager.GetString("LocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Import 的本地化字符串。
        /// </summary>
        public static string ManualImport {
            get {
                return ResourceManager.GetString("ManualImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest Time 的本地化字符串。
        /// </summary>
        public static string MaxTime {
            get {
                return ResourceManager.GetString("MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member 的本地化字符串。
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Members 的本地化字符串。
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Short Message 的本地化字符串。
        /// </summary>
        public static string MessageShort {
            get {
                return ResourceManager.GetString("MessageShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Earliest Time 的本地化字符串。
        /// </summary>
        public static string MinTime {
            get {
                return ResourceManager.GetString("MinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile Number 的本地化字符串。
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operations 的本地化字符串。
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent 的本地化字符串。
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Period 的本地化字符串。
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Name 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repositories 的本地化字符串。
        /// </summary>
        public static string Repositories {
            get {
                return ResourceManager.GetString("Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository URL : 的本地化字符串。
        /// </summary>
        public static string RepositoryUrl {
            get {
                return ResourceManager.GetString("RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sha 的本地化字符串。
        /// </summary>
        public static string Sha {
            get {
                return ResourceManager.GetString("Sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Short Sha 的本地化字符串。
        /// </summary>
        public static string ShaShort {
            get {
                return ResourceManager.GetString("ShaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Student Number 的本地化字符串。
        /// </summary>
        public static string StudentNumber {
            get {
                return ResourceManager.GetString("StudentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team Info 的本地化字符串。
        /// </summary>
        public static string TeamInfo {
            get {
                return ResourceManager.GetString("TeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team Name 的本地化字符串。
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Time 的本地化字符串。
        /// </summary>
        public static string TimeOriginal {
            get {
                return ResourceManager.GetString("TimeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkSpace 的本地化字符串。
        /// </summary>
        public static string WorkSpace {
            get {
                return ResourceManager.GetString("WorkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load WorkSpace 的本地化字符串。
        /// </summary>
        public static string WorkSpaceLoad {
            get {
                return ResourceManager.GetString("WorkSpaceLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save WorkSpace 的本地化字符串。
        /// </summary>
        public static string WorkSpaceSave {
            get {
                return ResourceManager.GetString("WorkSpaceSave", resourceCulture);
            }
        }
    }
}
